apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "fbs-d.com": [
        "10.157.201.5",
        "10.157.202.5",
        "10.157.203.5"
      ]
    }
